# Generated by Django 2.0.2 on 2018-03-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='code',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=65, unique=True),
        ),
    ]
